services:
    blog-db:
        container_name: blog-db
        build: ./db_config
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - blog-net
        tty: true
        restart: on-failure
    blog-app:
        container_name: blog-app
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: development
        # RUN in debug mode: yarn start:debug --> Also start your debugger
        # Run in dev mode: yarn start:dev
        command: yarn start:debug
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - .env
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${DEBUG_PORT}:${DEBUG_PORT}
        networks:
            - blog-net
        depends_on:
            - blog-db
        restart: on-failure

volumes:
    pgdata:
        driver: local
    blog-app: {}

networks:
    blog-net:
        driver: bridge
