# fly.toml app configuration file generated for first-blog-app on 2023-05-15T03:02:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "first-blog-app"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
